### ISSUE TITLE
Add ability to write reviews on games and leave the stars for the game as rating.

### ISSUE THREAD

**Issue by SEM24** [GRID-Game-Store/backend#14]

**Comment by kirillserebrykov** [comment]
бек нахуй упал 🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡🤡
просто нахуй пол бека не ебашит 


![Image](https://github.com/GRID-Game-Store/backend/assets/60855065/635231ac-f710-4775-a3ba-ebf75b48fd63)
