### ISSUE TITLE
Add docker compose file and docker file to have a MySql db in docker, so frontend can use backend

### ISSUE THREAD

**Issue by SEM24** [GRID-Game-Store/backend#17]
**PROJECT CONFIGURATION CREDENTIALS:** DB_USERNAME=spring;DB_PASSWORD=spring;DB_URL=jdbc:mysql://localhost:3307/GridDB?allowPublicKeyRetrieval=true&useSSL=false

**BEFORE USING THE BACKEND, USE THIS COMMANDS FIRST (after docker-compose file was executed):**

1. Enter the MySQL container:
docker exec -it my-mysql-container bash

2. Connect to MySQL using the command:
mysql -u root -pspring

3. Next, grant privileges to the user 'spring' on the 'GridDB' database. Execute the following SQL query:
GRANT ALL PRIVILEGES ON GridDB.* TO 'spring'@'%';
FLUSH PRIVILEGES;

4. Exit MySQL and the container:
exit
exit

**Comment by kirillserebrykov** [comment]
https://github.com/GRID-Game-Store/documentation-/blob/main/backend/docker.md
