### ISSUE TITLE
1.1 A guest can be able to see a list of games with general information on main page

### ISSUE THREAD

**Issue by SEM24** [GRID-Game-Store/backend#2]
In list, guest can see the information such as:

- game's banner
- title
- tags(labels)
- price
- publisher
- developer
- genres
- description

**Comment by kirillserebrykov** [comment]
In the list, guests can see information such as:
Header with search, logo, and other
Slider with popular games
One block with the genre
Section with 3 tabs "top selling", "new" and  ------, which can show games according to tab,
Block with 20 random games 
A guest can search games and see full information about games by clicking on the game
