### ISSUE TITLE
Write the endpoint that returns n number of games, randomly picked up from db

### ISSUE THREAD

**Issue by SEM24** [GRID-Game-Store/backend#20]
**GetMapping: localhost:8082/api/v1/games/random?qty=1**

**Comment by kirillserebrykov** [comment]
change schema response and change name endpoint from random to "most popular games" 
  id: number;
  title: string;
  description: string;
  //!release_date: string;
  //!system_requirements: string;
  price: number;
  cover_image_url: string;
  publisher: MetaData;
  developer: MetaData;
  tags: Array<MetaData>; //* only 3 tags
  genres: Array<MetaData>;
  platforms: Array<MetaData>;

**Comment by kirillserebrykov** [comment]
for popular games, the slider needs large cover

**Comment by kirillserebrykov** [comment]
**Does not have** 
genres: Array;
platforms: Array;
